# sitemap settings

template: sitemap.twig
xml_template: sitemap_xml.twig

ignore:
  - /acces-bureau
  - /documents-divers
  - /accueil/bienvenue-au-club

## ignore by "slug" of contenttype
#ignore_contenttype:
#  - pages

## listing routes (contenttype_slug: route_name)
#listing_routes:
#  pages: custom_pages_route

## ignore listing templates
ignore_listing: true

## ignore images (by default the sitemap contains links to images)
ignore_images: true

## when ignore_listing is not = true: listings templates may not exist yet may contain child pages.
## add path will keep listing visible in tree but remove its link.
#remove_link:
#  - /pages
