version: '3.3'

services:
  mysql:
    container_name: asmb_mysql
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - asmb
    ports:
      - 3306:3306
    expose:
      - 3306

  php-apache:
    container_name: asmb_php
    build:
      context: .
      dockerfile: docker/php-apache/Dockerfile
      args:
        - UID=1000
        - GID=1000
    environment:
      PHP_IDE_CONFIG: serverName=asmb
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./bolt/:/var/www/html/
    networks:
      - asmb

networks:
  asmb:
    driver: bridge

volumes:
  dbdata:
    driver: local
