# This file defines the contenttypes on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

# The Homepage contenttype is a singleton: There can be only one record of this
# contenttype.

homepage:
    name: "Accueil"
    singular_name: "Accueil"
    fields:
        # Onglet Contenu
        title:
            group: contenu
            label: 'Titre'
            type: text
            class: large

        teaser:
            label: 'Accroche'
            type: html
            height: 150px
            postfix: |
                Si ce champ est renseigné, son contenu s'affiche <b>avant</b> les blocs de l'accueil.
        teaser_image:
            label: 'Image de l''accroche'
            type: image
        blocks_top:
            label: 'Blocs du haut'
            type: repeater
            limit: 3
            prefix: 'Ces blocs sont affichés <b>avant</b> les rencontres du moment.'
            fields:
                block:
                    label: 'Bloc'
                    type: select
                    values: (blocks,competition_blocks)/title
                    filter: { status: published }

        meetings_past_days:
            label: 'Nb jours passés'
            prefix: Afficher les résultats des rencontres de ce nb de jours passés.
            type: integer
            default: 14
            min: 0
            max: 60

        meetings_future_days:
            label: 'Nb jours à venir'
            prefix: Afficher les prochaines rencontres de ce nb de jours à venir.
            type: integer
            default: 7
            min: 0
            max: 30

        blocks_bottom:
            label: 'Blocs du bas'
            type: repeater
            limit: 3
            prefix: 'Ces blocs sont affichés <b>après</b> les rencontres du moment.'
            fields:
                block:
                    label: 'Bloc'
                    type: select
                    values: (blocks,competition_blocks)/title
                    filter: { status: published }

        # Onglet Propriétés
        slug:
            group: meta
            type: slug
            uses: title

        # Onglet En-tête du site : personnalisation de certains éléments de l'en-tête
        header_title:
            group: en-tête du site
            label: 'Titre'
            type: text
            required: true
            postfix: |
                Peut contenir des balises HTML. Les lettres mises entre les balises &lt;strong&gt;&lt;/strong&gt; sont
                mises en avant (taille plus grande + autre couleur).

        header_baseline:
            label: 'Accroche du site'
            type: text
            required: true

        header_fft_number:
            label: 'Numéro FFT'
            type: text
            required: true

        header_location_text:
            label: 'Adresse postale'
            type: text
            required: true

        header_location_url:
            label: 'Url vers la page du plan d''accès'
            type: text
            required: true
            postfix: |
                Url relative au site

        header_contact_text:
            label: 'Libellé contact'
            type: text
            required: true

        header_contact_url:
            label: 'Url vers la page de contact'
            type: text
            required: true
            postfix: |
                Url relative au site

        header_facebook_text:
            label: 'Libellé Facebook'
            type: text

        header_facebook_url:
            label: 'Url Facebook'
            type: text

        header_book_url:
            label: 'Url de réservation'
            type: text
            required: true
            postfix: |
                Ouvert dans un nouvel onglet/une nouvelle fenêtre.

        # Onglet Pied de page du site : personnalisation de certains éléments du pied de page
        footer_contact_address_text:
            group: pied de page du site
            label: Adresse du club
            type: textarea
            required: true
            height: 100px
            postfix: |
                Peut contenir des balises HTML.

        footer_contact_location_link_text:
            label: Plan d'accès au club - Libellé du lien
            type: text
            required: true

        footer_contact_location_link_url:
            label: Plan d'accès au club - URL du lien
            type: text
            required: true

        footer_contact_link_text:
            label: Page de contact - Libellé du lien
            type: text
            required: true

        footer_contact_link_url:
            label: Page de contact - URL du lien
            type: text
            required: true

        footer_book_slot_url:
            label: Réservation d'un créneau - URL du lien
            type: text
            required: true

        footer_membership_link_text:
            label: Page d'inscription: Libellé du lien
            type: text
            required: true

        footer_membership_url:
            label: Page d'inscription: URL du lien
            type: text
            required: true

        footer_facebook_link_url:
            label: Page Facebook: URL du lien
            type: text
            required: true
    viewless: true
    singleton: true
    default_status: published
    icon_many: "fa:home"
    icon_one: "fa:home"

blocks:
    name: Blocs
    singular_name: Bloc
    singular_slug: block
    fields:
        title:
            type: text
            label: 'Titre'
            class: large
            required: true
            group: "Contenu"
        subtitle:
            type: text
            label: 'Sous-titre'
            class: large
        image:
            type: image
            label: 'Image (décorative) du bloc'
            attrib: title
            extensions: [ gif, jpg, png ]
            required: true
        image_width:
            type: integer
            label: 'Largeur de l''image décorative'
            options:
                min: 200
                max: 500
                step: 10
            required: true
        image_height:
            type: integer
            label: 'Hauteur de l''image décorative'
            options:
                min: 300
                max: 700
                step: 10
            required: true
        content:
            type: html
            label: 'Contenu du bloc'
            height: 300px
            options:
                ckeditor:
                    fillEmptyBlocks: true
            required: true
        contentlink:
            type: text
            label: 'Lien'
            placeholder: Un lien relatif au site (ex: "contenttype/slug") ou absolu (ex: "http://example.org/")
            postfix: "Ajoute un lien sur ce bloc vers une page. Ce peut être un lien interne relatif (ex: <tt>page/contact</tt>) ou un lien externe absolu (ex: `https://www.fft.fr/`)."
        contentlink_label:
            type: text
            label: 'Libellé du lien'
        slug:
            type: slug
            uses: [ title ]
    show_on_dashboard: true
    viewless: true
    default_status: published
    record_template: partials/block/_block.twig
    searchable: false
    icon_many: "fa:cubes"
    icon_one: "fa:cube"

competition_blocks:
    name: Blocs compétition
    singular_name: Bloc compétition
    singular_slug: competition_block
    fields:
        title:
            type: text
            label: 'Titre de la compétition'
            class: large
            required: true
            group: "Contenu"
            postfix: 'Ex: "Tournoi ASMB 2019 de printemps", "TMC Dames ASMB 2019"'
        image:
            type: image
            label: 'Image (décorative) du bloc'
            attrib: title
            extensions: [ gif, jpg, png ]
            required: true
        image_width:
            type: integer
            label: 'Largeur de l''image décorative'
            options:
                min: 200
                max: 500
                step: 10
            required: true
        image_height:
            type: integer
            label: 'Hauteur de l''image décorative'
            options:
                min: 300
                max: 700
                step: 10
            required: true
        subtitle:
            type: text
            label: 'Sous-titre'
            class: large
            required: true
            placeholder: 'Dates de la compétition'
            postfix: 'Ex:<br>Du 28 mars au 7 avril'
        subtitle2:
            type: text
            label: 'Sous-titre 2'
            class: large
            placeholder: 'Catégorie(s) concernée(s)'
            postfix: 'Ex:<br>Deux tournois en parallèle : 3ème et 4ème série'
        balls_provided:
            label: 'Infos sur balles à afficher'
            type: select
            values: { 'no': 'balles non fournies', 'yes_head': 'Balles HEAD fournies', 'yes': 'Balles fournies' }
        location:
            label: 'Lieu de compétition'
            type: textarea
            postfix: 'Ex:<br>Halle de tennis et courts extérieurs<br>du complexe Mangin Beaulieu<br>au 2 rue des Boires à Nantes'
        schedule:
            label: 'Horaires des matchs'
            type: textarea
            postfix: 'Ex:<br>En semaine, à partir de 17h30 et le week-end de 9h à 22h.<br>Des matchs pourront être programmés en journée la semaine pour ceux qui le peuvent.'

        inscriptions:
            label: 'Inscriptions'
            type: repeater
            fields:
                text:
                    label: 'Élément d''information'
                    type: textarea

        inscriptions_closing_without_notice:
            label: 'Afficher "clôture sans préavis"'
            type: checkbox

        commitment_rights:
            label: 'Droits d''engagement'
            type: repeater
            fields:
                text:
                    label: 'Élément d''information'
                    type: textarea

        contentlink:
            type: text
            label: 'Lien'
            placeholder: Un lien relatif au site (ex: "contenttype/slug") ou absolu (ex: "http://example.org/")
            postfix: "Ajoute un lien sur ce bloc vers une page. Ce peut être un lien interne relatif (ex: <tt>page/contact</tt>) ou un lien externe absolu (ex: `https://www.fft.fr/`)."
        contentlink_label:
            type: text
            label: 'Libellé du lien'
        slug:
            type: slug
            uses: [ title ]
    show_on_dashboard: true
    viewless: true
    default_status: published
    searchable: false
    record_template: partials/block/_competition_block.twig
    icon_many: "fa:cubes"
    icon_one: "fa:cube"

pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
            placeholder: https://source.unsplash.com/1280x768/?business,workplace/__random__
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        template:
            type: templateselect
            filter: 'template_*.twig'
    record_template: template_page.twig
    recordsperpage: 20
    taxonomy: [ tags ]

evenements:
    name: Évènements
    singular_name: Évènement
    fields:
        title:
            label: Titre
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        from_date:
            label: Date et heure de l'évènement
            type: datetime
            required: true
        to_date:
            label: Date et heure de fin
            type: datetime
        location:
            label: Lieu
            type: text
        image:
            type: image
        short_text:
            label: Texte court
            type: html
            height: 200px
            options:
                ckeditor:
                    removeButtons: Image,Table,SpecialChar
        text:
            label: Texte
            type: html
            height: 400px
            options:
                ckeditor:
                    removeButtons: Image,Table,SpecialChar
    record_template: template_page.twig


competitions:
    name: Compétitions
    singular_name: Compétition
    fields:
        name:
            label: 'Nom de la page'
            type: text
            class: large
            group: content
        title:
            label: 'Titre affiché sur la page'
            type: text
            class: large
        slug:
            type: slug
            uses: title
        competition_id:
            type: integer
            label: ID (Bolt) de la compétition
        competition_categories:
            type: select
            values: ['Hommes','Dames','+35','Jeunes']
            label: Afficher uniquement les données de cette/ces catégorie(s)
            multiple: true
    icon_many: "fa:trophy"
    record_template: competitions.twig
    taxonomy: [ tags ]

calendriers:
    name: Calendriers
    singular_name: Calendrier
    show_in_menu: Calendriers
    fields:
        name:
            group: 'Général'
            label: 'Nom'
            type: text
            class: large
        slug:
            type: slug
            uses: name
        year:
            label: 'Année de début'
            type: text
            class: narrow
            pattern: "20[1-3][0-9]"
            error: Merci de saisir une année valide
            postfix: Le calendrier va de Septembre de l'année A à Juin de l'année A+1
            placeholder: "Ex: 2019"
        lessons_from_date:
            label: 'Date de début des cours collectifs'
            type: date
            required: true
            postfix: 'Les cours débutent en principe un lundi'
        lessons_to_date:
            label: 'Date de fin des cours collectifs'
            postfix: 'Les cours terminent en principe un samedi'
            type: date
            required: true
        holidays:
            label: 'Dates des petites vacances scolaires'
            prefix: 'Pour la zone B (Nantes)'
            type: repeater
            initial: 4
            limit: 4
            fields:
                name:
                    label: "Nom"
                    type: text
                    required: true
                holidays_from_date:
                    label: "Début"
                    type: date
                    required: true
                holidays_to_date:
                    label: "Fin"
                    type: date
                    required: true

        events:
            group: 'Événements'
            label: 'Événement'
            type: repeater
            fields:
                evt_title:
                    label: 'Nom'
                    type: text
                evt_type:
                    label: 'Type'
                    type: select
                    required: true
                    values: type_evenement_calendriers/name
                    sort: name
                    autocomplete: true
                evt_from_date:
                    label: "Début"
                    type: date
                    required: true
                evt_duration:
                    label: "Durée (en jours)"
                    type: integer
                    required: true
                    default: 1
                evt_with_lesson:
                    label: "Cours collectif durant l'événement"
                    type: checkbox
    taxonomy: [ tags ]
    icon_many: "fa:calendar"

type_evenement_calendriers:
    name: Types événement
    singular_name: Type événement
    viewless: true
    searchable: false
    show_in_menu: Calendriers
    default_status: published
    fields:
        name:
            label: "Libellé"
            type: text
            class: large
            group: content
        color:
            label: "Couleur"
            type: text
            class: large
            pattern: "#[0-9a-f]{6}"
            placeholder: "Ex: #aecf00"
        position:
            label: "Position"
            postfix: "Ordre d'apparition dans la légende des calendriers"
            type: integer
            class: narrow
    icon_many: "fa:tag"
