main:
    -
        path: page/editorial
        label: Éditorial
    -
        path: page/inscriptions
        label: Inscriptions
    -
        path: page/le-bureau
        label: 'Le Club'
        submenu:
            -
                path: page/terrains
                label: Terrains
            -
                path: page/le-bureau
                label: 'Le Bureau'
            -
                path: page/adherents
                label: Adhérents
            -
                path: page/reglement
                label: Règlement
    -
        path: page/competitions
        label: Compétitions
        submenu:
            -
                path: page/championnat
                label: Championnat
                submenu:
                    -
                        path: page/seniors-hommes
                        label: 'Seniors Hommes'
                    -
                        path: page/seniors-dames
                        label: 'Seniors Dames'
                    -
                        path: page/seniots-plus
                        label: 'Seniors Plus'
                    -
                        path: page/jeunes
                        label: Jeunes
                    -
                        path: page/championnat-d-ete
                        label: 'Championnat d''été'
            -
                path: page/tournois
                label: Tournois
    -
        path: page/tennis-loisir
        label: 'Tennis Loisir'
        submenu:
            -
                path: page/creneaux
                label: Créneaux
            -
                path: page/reservations
                label: Réservations
    -
        path: page/enseignement
        label: Enseignement
        submenu:
            -
                path: page/pour-plus-d-entrainement
                label: 'Pour plus d''entraînement'
            -
                path: page/prepa-physique-avant-saison
                label: 'Prépa. physique avant saison'
    -
        path: page/evenements
        label: Évènements
    -
        path: page/agenda
        label: Agenda
    -
        path: page/guides-pratiques
        label: 'Guides pratiques'
    -
        path: page/galerie-photos
        label: 'Galerie photos'

footer_contact:
    -
        label: 'Coordonnées'
        submenu:
            -
                label: '<address><span>Complexe Sportif </span><span>Mangin Beaulieu</span><br><span>2 rue des Boires, </span><span>44200 Nantes</span></address>'
                class: address
            -
                label: 'Nous localiser sur un plan'
                link: https://www.openstreetmap.org/?mlat=47.2050&mlon=-1.5431#map=14/47.2050/-1.5431
            -
                label: 'Nous contacter'
                path: page/contacts

footer_external_links:
    -
        label: 'Liens externes'
        class: liens-utiles
        submenu:
            -
                link: http://www.fft.fr/portail/default.asp
                label: 'Fédération Française de Tennis'
            -
                link: http://www.comite.fft.fr/loire-atlantique/02L00440_a/cms/index_public.php?us_action=show_note_site&login_off=1&ui_id_site=1
                label: 'Comité Départemental'
            -
                link: http://www.ligue.fft.fr/pays-loire/paysdelaloire_a/cms/index_public.php?PHPSESSID=0fe0c5d5881e834f19d3b15c90dc4e77&us_action=show_note_site&ui_id_site=1
                label: 'Ligue des Pays de Loire'
            -
                link: http://www.gs.applipub-fft.fr/fftfr/frameset.do?dispatch=load
                label: 'Gestion Sportive (Championnat)'
            -
                link: https://mon-espace-tennis.fft.fr/
                label: 'Mon espace tennis'
            -
                link: https://mon-espace-tennis.fft.fr/tournoi/82120115
                label: 'Championnat individuel'
            -
                link: http://www.ei.applipub-fft.fr/eipublic/competitionRecherche.do?dispatch=afficher
                label: 'Tournois FFT'
