main:
    - label: 'Le Club'
      path: page/edito
      submenu:
        - path: page/edito
          label: 'Édito'
        - path: page/terrains
          label: 'Terrains'
        - path: page/le-bureau
          label: 'Le Bureau'
        - path: page/quelques-chiffres
          label: 'Quelques chiffres'
        - path: page/reglement-interieur-2018-2019
          label: 'Règlement intérieur'

    - label: 'Jouer'
      path: page/inscriptions
      submenu:
        - label: 'Inscriptions & tarifs'
          path: page/inscriptions
          submenu:
            - label: 'Inscriptions'
              path: page/inscriptions
            - label: 'Tarifs'
              path: page/tarifs
        - label: 'Tennis Loisir'
          path: page/creneaux
          submenu:
            - label: 'La carte'
              path: page/nos-cartes-loisir
            - label: 'Créneaux'
              path: page/creneaux
            - label: 'Réservations'
              path: page/reservations

        - label: 'Plus d''entraînement'
          path: page/plus-d-entrainement

    - label: 'Compétitions'
      path: competition/championnat-ete
      submenu:
        - label: 'Championnat d''été'
          path: competition/championnat-ete

        - label: 'Coupe de printemps'
          path: competition/coupe-printemps

        - label: 'Championnats d''hiver'
          path: competition/seniors-hommes
          submenu:
            - label: 'Seniors Hommes'
              path: competition/seniors-hommes

            - label: 'Seniors Dames'
              path: competition/seniors-dames

            - label: 'Seniors Plus'
              path: competition/seniors-plus

            - label: 'Jeunes'
              path: competition/jeunes

        - label: 'Tournois'
          path: page/tournois

    - label: 'Actualités'
      path: page/evenements
      submenu:
        - label: 'Évènements'
          path: page/evenements

        - label: 'Calendrier'
          path: calendrier/2018-2019

#        - label: 'Galerie photos'
#          path: page/galerie-photos


    - label: 'Documentations'
      path: tags/infos-pratiques
      submenu:
        - label: 'Infos pratiques'
          path: tags/infos-pratiques

        - label: 'Documents divers'
          path: tags/documents-divers

        - label: 'Histoire du Tennis'
          path: page/le-jeu-de-paume
          submenu:
            - label: 'Le jeu de Paume'
              path: page/le-jeu-de-paume
            - label: 'Invention du Lawn-Tennis'
              path: page/invention-du-lawn-tennis
            - label: 'Conquête du Lawn-Tennis'
              path: page/conquete-du-lawn-tennis
            - label: 'Tennis Moderne'
              path: page/tennis-moderne


footer_external_links:
    - label: 'Liens externes'
      class: liens-utiles
      submenu:
        - label: 'Fédération Française de Tennis'
          link: https://www.fft.fr

        - label: 'Comité Départemental'
          link: http://www.comite.fft.fr/loire-atlantique/02L00440_a/cms/index_public.php?us_action=show_note_site&login_off=1&ui_id_site=1

        - label: 'Ligue des Pays de Loire'
          link: http://www.ligue.fft.fr/pays-loire/pays-loire_a/cms/index_public.php?us_action=show_note_site&login_off=1&ui_id_site=1

        - label: 'Gestion Sportive (Championnat)'
          link: http://www.gs.applipub-fft.fr/fftfr/frameset.do?dispatch=load

        - label: 'Mon espace tennis'
          link: https://mon-espace-tennis.fft.fr/

        - label: 'Championnat individuel'
          link: https://mon-espace-tennis.fft.fr/tournoi/82120115

        - label: 'Rechercher une compétition'
          link: https://tenup.fft.fr/recherche/tournois/all?dispatch=afficher
