main:
  - label: 'Le Club'
    path: le-club
    submenu:
      - label: 'Infrastructures'
        path: le-club/infrastructures
      - label: 'Le bureau'
        path: le-club/le-bureau
      - label: 'Les chiffres'
        path: le-club/les-chiffres
      - label: 'Règlement intérieur'
        path: le-club/reglement-interieur
      - label: 'Nos partenaires'
        path: le-club/nos-partenaires

  - label: 'Jouer'
    path: page/inscriptions
    submenu:
      - label: 'Inscriptions'
        path: page/inscriptions
      - label: 'Formules et tarifs'
        path: page/tarifs
      - label: 'Nos cartes loisirs'
        path: page/tennis-loisir-carte
      - label: 'Réservation'
        path: page/tennis-loisir-reservation
      - label: 'Les créneaux'
        path: page/tennis-loisir-creneaux
     

  - label: 'Compétitions'
    path: competitions/
    submenu:
      - label: 'Championnats & Coupes'
        path: competitions/championnat-regional-2022-2023
        submenu:
          - label: 'Championnat régional'
            path: competitions/championnat-regional-2022-2023
          - label: 'Championnat départemental'
            path: competitions/championnat-departemental-2022-2023

      - label: 'Planning des rencontres par équipe'
        path: competitions/planning-des-rencontres-par-equipe
        
      - label: 'Rencontres à domicile'
        path: competitions/rencontres-a-domicile

      #- label: 'Tournois'
      #  path: competition/tournoi-open-ete-2022
      #  submenu:   
        
      - label: '[Archives] Saison 2021-2022'
        submenu:
          - label: 'Championnats & Coupes'
            submenu:
            - label: 'Championnat d''Hiver'
              path: competitions/championnat-d-hiver-2021-2022
            - label: 'Coupe d''Hiver féminine'
              path: competitions/coupe-d-hiver-feminine-2021-2022
            - label: 'Championnat découverte'
              path: competitions/championnat-decouverte-2022          
            - label: 'Championnat de Printemps'
              path: competitions/championnat-de-printemps-2022
          - label: 'Tournois'
            path: competitions/tournoi-open-ete-2022
            submenu:
            - label: 'Trophée Philippe Le Gouic 2021'
              path: competitions/trophee-philippe-le-gouic-2021          
            - label: 'Open février 2022'
              path: competitions/tournoi-open-fevrier-2022
            - label: 'Open été 2022'
              path: competitions/tournoi-open-ete-2022
            - label: 'ASMB Cup'
              path: competitions/asmb-cup-2022#res

      - label: '[Archives] Saison 2020-2021'
        path: competitions/tournoi-open-ete-2021
        submenu:
          - label: 'Tournoi Open été 2021'
            path: competitions/tournoi-open-ete-2021
          - label: 'ASMB Cup 2021'
            path: competitions/asmb-cup-2021
          - label: 'Trophée Philippe Le Gouic 2020'
            path: competitions/trophee-philippe-le-gouic-2020
          - label: 'Tournoi interne de reprise 2020'
            path: competitions/tournoi-interne-de-reprise-2020

      - label: '[Archives] Saison 2019-2020'
        submenu:
          - label: 'TMC 13/14 ans mars 2020'
            path: competitions/tmc-13-14-ans-2020
          - label: 'Tournoi Open Messieurs février 2020'
            path: competitions/tournoi-open-messieurs-fevrier-2020
          - label: 'Trophée Philippe Le Gouic 2019'
            path: competitions/trophee-philippe-le-gouic-2019

  #    - label: 'Actualités'
  #      path: page/evenements
  #      submenu:
  #        - label: 'Événements'
  #          path: page/evenements
  #
  #        - label: 'Calendrier'
  #          path: calendrier/2018-2019
  #
  #        - label: 'Galerie photos'
  #          path: page/galerie-photos


  - label: 'Publications'
    path: tags/infos-pratiques
    submenu:
      - label: 'Infos pratiques'
        path: tags/infos-pratiques

      - label: 'Documents divers'
        path: document-divers/tous

      - label: 'Histoire du Tennis'
        path: page/le-jeu-de-paume
        submenu:
          - label: 'Le jeu de Paume'
            path: page/le-jeu-de-paume
          - label: 'Invention du Lawn-Tennis'
            path: page/invention-du-lawn-tennis
          - label: 'Conquête du Lawn-Tennis'
            path: page/conquete-du-lawn-tennis
          - label: 'Tennis Moderne'
            path: page/tennis-moderne

  - label: 'Calendrier'
    path: calendrier

footer_external_links:
  - label: 'Liens externes'
    class: liens-utiles
    submenu:
      - label: 'Mon espace tennis'
        link: https://tenup.fft.fr/

      - label: 'Fédération Française de Tennis'
        link: https://www.fft.fr

      - label: 'Comité Départemental'
        link: http://www.comite.fft.fr/loire-atlantique/02L00440_a/cms/index_public.php?us_action=show_note_site&login_off=1&ui_id_site=1

      - label: 'Ligue des Pays de Loire'
        link: http://www.ligue.fft.fr/pays-loire/pays-loire_a/cms/index_public.php?us_action=show_note_site&login_off=1&ui_id_site=1

      - label: 'Rechercher une compétition par équipe'
        link: https://tenup.fft.fr/recherche/equipes

      - label: 'Rechercher un tournoi'
        link: https://tenup.fft.fr/recherche/tournois
