# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

#home_flags:
#    name: Indicateurs accueil
#    singular_name: Indicateur accueil
#    slug: home_flags
#    singular_slug: home_flag
#    behaves_like: grouping
#    multiple: false
#    options:
#        accueil-top: Affiché sur l'accueil - section du haut
#        accueil-bottom: Afficher sur l'accueil - section du bas
#    has_sortorder: true

tags:
    name: Tags
    singular_name: Tag
    slug: tags
    singular_slug: tag
    behaves_like: grouping
    multiple: false
    options:
        archives-competitions-equipe: "Archives des compétitions par équipe"
        archives-tournois: "Archives des tournois organisés par le club"
        calendrier: Calendrier
        histoire-tennis: Histoire du tennis
        infos-pratiques: Infos pratiques
        reglement: Règlement intérieur
        statistiques: Statistiques
    has_sortorder: true

#tags:
#    slug: tags
#    singular_slug: tag
#    behaves_like: tags
#    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
#    allow_spaces: false
#    #listing_template: tag-listing.twig #custom template
#
#groups:
#    slug: groups
#    singular_slug: group
#    behaves_like: grouping
#    options: { main: "Le Club", meta: "Meta group", other: "The other stuff" }
#    has_sortorder: true
#
#categories:
#    name: Categories
#    slug: categories
#    singular_name: Category
#    singular_slug: category
#    behaves_like: categories
#    multiple: true
#    options: [ news, events, movies, music, books, life, love, fun ]
